PRODUCT_DEFAULT_DEV_CERTIFICATE := vendor/yaap/signing/keys/releasekey
PRODUCT_MAINLINE_SEPOLICY_DEV_CERTIFICATES := vendor/yaap/signing/keys
PRODUCT_MAINLINE_BLUETOOTH_SEPOLICY_DEV_CERTIFICATES := vendor/yaap/signing/keys
