PRODUCT_DEFAULT_DEV_CERTIFICATE := vendor/yaap-priv/keys/releasekey
PRODUCT_MAINLINE_SEPOLICY_DEV_CERTIFICATES := vendor/yaap-priv/keys
PRODUCT_MAINLINE_BLUETOOTH_SEPOLICY_DEV_CERTIFICATES := vendor/yaap-priv/keys
