PRODUCT_DEFAULT_DEV_CERTIFICATE := vendor/miku-secret/keys/releasekey
PRODUCT_MAINLINE_SEPOLICY_DEV_CERTIFICATES := vendor/miku-secret/keys
PRODUCT_MAINLINE_BLUETOOTH_SEPOLICY_DEV_CERTIFICATES := vendor/miku-secret/keys
